apiVersion: apps/v1
kind: Deployment
metadata:
  name: $NAME
  labels:
    app.kubernetes.io/name: backend
    app.kubernetes.io/version: $VERSION
    iter8.tools/track: $TRACK
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: backend
      iter8.tools/track: $TRACK
  template:
    metadata:
      labels:
        app.kubernetes.io/name: backend
        iter8.tools/track: $TRACK
    spec:
      containers:
      - name: backend
        image: kalantar/backend:$VERSION
        env:
        - name: MY_VERSION
          value: $VERSION
        resources: {}
---
apiVersion: v1
kind: Service
metadata:
  name: $NAME
spec:
  selector:
    app.kubernetes.io/name: backend
    iter8.tools/track: $TRACK
  ports:
  - port: 8091
