apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app.kubernetes.io/name: backend
    app.kubernetes.io/version: v1
    iter8.tools/abn: "true"
    iter8.tools/track: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: backend
      iter8.tools/track: default
  template:
    metadata:
      labels:
        app.kubernetes.io/name: backend
        iter8.tools/track: default
    spec:
      containers:
      - name: backend
        image: BACKEND_TAG
        env:
        - name: VERSION
          value: v1
        resources: {}
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app.kubernetes.io/name: backend
    iter8.tools/track: default
  ports:
  - port: 8091
