# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: abn.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tabn.proto\x12\x04main\x1a\x1bgoogle/protobuf/empty.proto\")\n\x0b\x41pplication\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04user\x18\x02 \x01(\t\".\n\x15VersionRecommendation\x12\x15\n\rversionNumber\x18\x01 \x01(\x05\"M\n\x0bMetricValue\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\x12\x13\n\x0b\x61pplication\x18\x03 \x01(\t\x12\x0c\n\x04user\x18\x04 \x01(\t2}\n\x03\x41\x42N\x12:\n\x06Lookup\x12\x11.main.Application\x1a\x1b.main.VersionRecommendation\"\x00\x12:\n\x0bWriteMetric\x12\x11.main.MetricValue\x1a\x16.google.protobuf.Empty\"\x00\x42\'Z%github.com/iter8-tools/iter8/abn/grpcb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'abn_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z%github.com/iter8-tools/iter8/abn/grpc'
  _globals['_APPLICATION']._serialized_start=48
  _globals['_APPLICATION']._serialized_end=89
  _globals['_VERSIONRECOMMENDATION']._serialized_start=91
  _globals['_VERSIONRECOMMENDATION']._serialized_end=137
  _globals['_METRICVALUE']._serialized_start=139
  _globals['_METRICVALUE']._serialized_end=216
  _globals['_ABN']._serialized_start=218
  _globals['_ABN']._serialized_end=343
# @@protoc_insertion_point(module_scope)
