name: Publish A/B/n Sample Docker images

on:
  workflow_dispatch:
  # release:
  #   types: [published]
  #   paths:
  #   - samples/abn-sample

jobs:
  build-and-push-backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Get version
      run: |
        tagref=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
        # Strip "v" prefix from tagref
        echo "VERSION=$(echo $tagref | sed -e 's/^v//')" >> $GITHUB_ENV
        echo "MAJOR_MINOR_VERSION=$(echo $tagref | sed -e 's/^v//' -e 's,\([0-9]*\.[0-9]*\)\.\([0-9]*\),\1,')" >> $GITHUB_ENV
    - name: Get owner
      run: |
        ownerrepo=${{ github.repository }}
        owner=$(echo $ownerrepo | cut -f1 -d/)
        if [[ "$owner" == "iter8-tools" ]]; then
          owner=iter8
        fi
        echo "OWNER=$owner" >> $GITHUB_ENV
    - uses: docker/setup-buildx-action@v2
    - uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_SECRET }}
    - uses: docker/build-push-action@v3
      with:
        tags: ${{ env.OWNER }}/abn-sample-backend:${{ env.VERSION }},${{ env.OWNER }}/abn-sample-backend:${{ env.MAJOR_MINOR_VERSION }},${{ env.OWNER }}/abn-sample-backend:latest
        file: samples/abn-sample/backend/Dockerfile
        push: true

  build-and-push-frontends:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        lang: [go, node, python]
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Get version
      run: |
        tagref=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
        # Strip "v" prefix from tagref
        echo "VERSION=$(echo $tagref | sed -e 's/^v//')" >> $GITHUB_ENV
        echo "MAJOR_MINOR_VERSION=$(echo $tagref | sed -e 's/^v//' -e 's,\([0-9]*\.[0-9]*\)\.\([0-9]*\),\1,')" >> $GITHUB_ENV
    - name: Get owner
      run: |
        ownerrepo=${{ github.repository }}
        owner=$(echo $ownerrepo | cut -f1 -d/)
        if [[ "$owner" == "iter8-tools" ]]; then
          owner=iter8
        fi
        echo "OWNER=$owner" >> $GITHUB_ENV
    - uses: docker/setup-buildx-action@v2
    - uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_SECRET }}
    - uses: docker/build-push-action@v3
      with:
        tags: ${{ env.OWNER }}/abn-sample-frontend-${{ matrix.lang }}:${{ env.VERSION }},${{ env.OWNER }}/abn-sample-frontend-${{ matrix.lang }}:${{ env.MAJOR_MINOR_VERSION }},${{ env.OWNER }}/abn-sample-frontend-${{ matrix.lang }}:latest
        file: samples/abn-sample/frontend/${{ matrix.lang }}/Dockerfile
        push: true

