name: end-to-end tests

on:
  pull_request:
  workflow_dispatch:


jobs:
  load-test-http:
    name: local httpbin tests
    runs-on: ubuntu-latest
    steps:
    - name: run httpbin
      run: |
        set -e
        docker pull kennethreitz/httpbin
        docker run -p 80:80 kennethreitz/httpbin &
        while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' http://127.0.0.1/get)" != "200" ]]; do
          sleep 5; 
        done;

    - name: load test GET endpoint
      run: | 
        cat << EOF > experiment-config.yaml
          url: http://127.0.0.1/get
        EOF
    - uses: iter8-tools/iter8-action@main
      with:
        chart: load-test-http
        valuesFile: experiment-config.yaml

    - name: load test GET endpoint
      run: | 
        cat << EOF > experiment-config.yaml
          url: http://127.0.0.1/get
          SLOs:
            http/latency-p25: 80
            http/latency-p50: 100
            http/latency-p95.0: 200
        EOF
    - uses: iter8-tools/iter8-action@main
      with:
        chart: load-test-http
        valuesFile: experiment-config.yaml

    - name: load test POST endpoint
      run: | 
        cat << EOF > experiment-config.yaml
          url: http://127.0.0.1/post
          payloadURL: https://cdn.pixabay.com/photo/2021/09/08/17/58/poppy-6607526_1280.jpg
          contentType: "image/jpeg"
          SLOs:
            http/latency-p25: 80
            http/latency-p50: 100
            http/latency-p95.0: 200
        EOF
    - uses: iter8-tools/iter8-action@main
      with:
        chart: load-test-http
        valuesFile: experiment-config.yaml

  e2e-load-test-grpc:
    name: local grpc tests
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: run greeter
      run: |
        git clone -b v1.43.0 https://github.com/grpc/grpc-go
        cd grpc-go/examples/helloworld
        go build greeter_server/main.go
        ./main &
        
    - name: load test grpc service method
      run: | 
        cat << EOF > experiment-config.yaml
          host: "127.0.0.1:50051"
          call: "helloworld.Greeter.SayHello"
          protoURL: "https://raw.githubusercontent.com/grpc/grpc-go/master/examples/helloworld/helloworld/helloworld.proto"
          data.name: "frodo"
          SLOs:
            grpc/error-rate: 0
            grpc/latency/mean: 50
            grpc/latency/p90: 100
            grpc/latency/p97.5: 200
        EOF
    - uses: iter8-tools/iter8-action@main
      with:
        chart: load-test-grpc
        valuesFile: experiment-config.yaml
