name: end-to-end tests

on:
  pull_request:

jobs:
  load-test-http:
    name: local httpbin tests
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Install Iter8
      run: |
        git clone https://github.com/sriumcp/iter8.git
        cd iter8
        git checkout initialv0.9
        make install    

    - name: run httpbin
      run: |
        set -e
        docker pull kennethreitz/httpbin
        docker run -p 80:80 kennethreitz/httpbin &
        while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' http://127.0.0.1/get)" != "200" ]]; do
          sleep 5; 
        done;

    - name: get charts
      run: |
        git clone https://github.com/sriumcp/hub.git
        cd hub
        git checkout ci

    - name: load test GET endpoint
      run: |
        set -e
        cd hub/charts/load-test-http
        iter8 gen --set url=http://127.0.0.1/get
        cat experiment.yaml
        iter8 run
        iter8 report
        iter8 assert -c completed -c nofailure -c slos

    - name: load test GET endpoint
      run: |
        set -e
        cd hub/charts/load-test-http
        iter8 gen --set url=http://127.0.0.1/get \
                  --set SLOs.http/latency-p25=80 \
                  --set SLOs.http/latency-p50=100 \
                  --set SLOs.http/latency-'p95\.0'=200
        cat experiment.yaml
        iter8 run
        iter8 report
        iter8 assert -c completed -c nofailure -c slos

    - name: load test POST endpoint (image/jpeg)
      run: |
        set -e
        cd hub/charts/load-test-http
        iter8 gen --set url=http://127.0.0.1/post \
                  --set payloadURL=https://cdn.pixabay.com/photo/2021/09/08/17/58/poppy-6607526_1280.jpg \
                  --set contentType="image/jpeg" \
                  --set SLOs.http/latency-p25=80 \
                  --set SLOs.http/latency-p50=100 \
                  --set SLOs.http/latency-'p95\.0'=200
        cat experiment.yaml
        iter8 run
        iter8 report
        iter8 assert -c completed -c nofailure -c slos

  e2e-load-test-grpc:
    name: local grpc tests
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Install Iter8
      run: |
        git clone https://github.com/sriumcp/iter8.git
        cd iter8
        git checkout initialv0.9
        make install    

    - name: run greeter
      run: |
        git clone -b v1.43.0 https://github.com/grpc/grpc-go
        cd grpc-go/examples/helloworld
        go build greeter_server/main.go
        ./main &

    - name: get charts
      run: |
        git clone https://github.com/sriumcp/hub.git
        cd hub
        git checkout ci
        
    - name: load test grpc service method
      run: |
        set -e
        cd hub/charts/load-test-grpc
        iter8 gen --set-string host="127.0.0.1:50051" \
                  --set-string call="helloworld.Greeter.SayHello" \
                  --set-string protoURL="https://raw.githubusercontent.com/grpc/grpc-go/master/examples/helloworld/helloworld/helloworld.proto" \
                  --set data.name="frodo" \
                  --set SLOs.grpc/error-rate=0 \
                  --set SLOs.grpc/latency/mean=50 \
                  --set SLOs.grpc/latency/p90=100 \
                  --set SLOs.grpc/latency/p'97\.5'=200
        cat experiment.yaml
        iter8 run
        iter8 report
        iter8 assert -c completed -c nofailure -c slos
